## emitc — nimony port of aowlc.js: post-hexer `.c.nif` → C. aowlc.js is the
## byte-identical ORACLE; emitjs.nim (~/aifjs/src) is the nifcursors API template.
##
## aowlc.js is a two-pass classify+emit design that relies on random access over
## an in-memory node tree. So this port first builds an AST (`Node`) from the
## streaming `Cursor`, then ports aowlc.js's logic directly against that AST.
when defined(nimony): {.feature: "lenientnils".}
import std/[syncio, os]
import nifcursors, nifstreams, nimony_model
import programs

const CPrelude* = """/* GENERATED BY aowlc. DO NOT EDIT. */
#define NIM_INTBITS 64
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <math.h>

#define NIM_NIL NULL
#define NB8 _Bool
typedef unsigned char NC8;
typedef uint16_t NC16;
typedef uint32_t NC32;
typedef float  NF32;
typedef double NF64;
typedef double NF;
typedef int8_t  NI8;  typedef int16_t  NI16; typedef int32_t  NI32; typedef int64_t  NI64;
typedef uint8_t NU8;  typedef uint16_t NU16; typedef uint32_t NU32; typedef uint64_t NU64;
typedef NI64 NI;      typedef NU64 NU;

#define NIM_TRUE true
#define NIM_FALSE false
#ifndef INF
#  ifdef INFINITY
#    define INF INFINITY
#  else
#    define INF (1.0/0.0)
#  endif
#endif
#if defined(__GNUC__) || defined(_MSC_VER)
#  define IL64(x) x##LL
#else
#  define IL64(x) ((NI64)x)
#endif
#define NIM_ALIGN(x)  __attribute__((aligned(x)))
#define NIM_ALIGNOF(x) __alignof__(x)
#if defined(__GNUC__) || defined(__clang__)
#  pragma GCC diagnostic ignored "-Wpointer-sign"
#  pragma GCC diagnostic ignored "-Wunused-label"
#  pragma GCC diagnostic ignored "-Wunused-variable"
#  pragma GCC diagnostic ignored "-Wunused-function"
#  pragma GCC diagnostic ignored "-Wformat"
#  pragma GCC diagnostic ignored "-Wdiscarded-qualifiers"
#  pragma GCC diagnostic ignored "-Wint-conversion"
#  pragma GCC diagnostic ignored "-Wincompatible-pointer-types"
#  pragma GCC diagnostic ignored "-Wbuiltin-declaration-mismatch"
#  pragma GCC diagnostic ignored "-Wimplicit-function-declaration"
#  pragma GCC diagnostic ignored "-Wmain"
#  pragma GCC diagnostic ignored "-Wreturn-type"
#  pragma GCC diagnostic ignored "-Wparentheses"
#  pragma GCC diagnostic ignored "-Wunused-but-set-variable"
#  pragma GCC diagnostic ignored "-Wmissing-braces"
#  pragma GCC diagnostic ignored "-Wattributes"
#endif
"""

# ---------------------------------------------------------------------------
# AST node (mirrors aowlc.js's readNif node shape)
# ---------------------------------------------------------------------------
type
  NKind = enum nkAtom, nkStr, nkChar, nkList
  Node = ref object
    kind: NKind
    tag: string          # list tag
    kids: seq[Node]
    atom: string         # atom text
    def: bool
    strVal: string       # string literal
    chrVal: int          # char literal code

proc isList(n: Node): bool = n != nil and n.kind == nkList
proc isAtom(n: Node): bool = n != nil and n.kind == nkAtom
proc isDot(n: Node): bool = isAtom(n) and n.atom == "."

proc fail(msg: string) =
  write stderr, msg & "\n"
  quit 1

# ---------------------------------------------------------------------------
# small string utilities (avoid depending on strutils subset surprises)
# ---------------------------------------------------------------------------
proc myRepeat(s: string; n: int): string =
  result = ""
  var i = 0
  while i < n:
    result.add s
    inc i

proc joinSeq(xs: seq[string]; sep: string): string =
  result = ""
  var first = true
  for x in xs:
    if not first: result.add sep
    first = false
    result.add x

proc splitLinesNl(s: string): seq[string] =
  result = @[]
  var cur = ""
  for ch in s:
    if ch == '\n':
      result.add cur
      cur = ""
    else:
      cur.add ch
  result.add cur

proc stripBoth(s: string): string =
  var a = 0
  var b = s.len - 1
  while a <= b and (s[a] == ' ' or s[a] == '\t' or s[a] == '\r' or s[a] == '\n'):
    inc a
  while b >= a and (s[b] == ' ' or s[b] == '\t' or s[b] == '\r' or s[b] == '\n'):
    dec b
  if a > b: return ""
  return s[a .. b]

proc beforeDot(s: string): string =
  var i = 0
  while i < s.len and s[i] != '.': inc i
  return s[0 ..< i]

proc oneOf(s: string; xs: openArray[string]): bool =
  for x in xs:
    if x == s: return true
  return false

proc toOctal(n: int): string =
  if n == 0: return "0"
  var v = n
  result = ""
  while v > 0:
    var d = ""
    d.add chr(ord('0') + (v mod 8))
    result = d & result
    v = v div 8

# ---------------------------------------------------------------------------
# literal detection / rendering (faithful to aowlc.js regexes)
# ---------------------------------------------------------------------------
proc isIntLit(a: string): bool =
  if a.len == 0: return false
  var i = 0
  if a[0] == '-': i = 1
  if i >= a.len: return false
  while i < a.len:
    if a[i] < '0' or a[i] > '9': return false
    inc i
  return true

proc isUIntLit(a: string): bool =
  if a.len == 0: return false
  var i = 0
  if a[i] < '0' or a[i] > '9': return false
  while i < a.len and a[i] >= '0' and a[i] <= '9': inc i
  if i >= a.len or a[i] != 'u': return false
  inc i
  if i == a.len: return true
  if a[i] == 'l':
    inc i
    if i == a.len: return true
    if a[i] == 'l':
      inc i
      return i == a.len
    return false
  return false

proc isFloatLit(a: string): bool =
  if a.len == 0: return false
  var i = 0
  if a[i] == '-': inc i
  var sawDigit = false
  while i < a.len and a[i] >= '0' and a[i] <= '9':
    inc i
    sawDigit = true
  if i < a.len and a[i] == '.':
    inc i
    while i < a.len and a[i] >= '0' and a[i] <= '9':
      inc i
      sawDigit = true
    if not sawDigit: return false
  else:
    if not sawDigit: return false
  if i < a.len and (a[i] == 'e' or a[i] == 'E'):
    inc i
    if i < a.len and (a[i] == '+' or a[i] == '-'): inc i
    if i >= a.len: return false
    var esaw = false
    while i < a.len and a[i] >= '0' and a[i] <= '9':
      inc i
      esaw = true
    if not esaw: return false
  if i != a.len: return false
  for ch in a:
    if ch == '.' or ch == 'e' or ch == 'E': return true
  return false

proc parseI64(s: string): int64 =
  var i = 0
  var neg = false
  if i < s.len and s[i] == '-':
    neg = true
    inc i
  var v: int64 = 0
  while i < s.len and s[i] >= '0' and s[i] <= '9':
    v = v * 10 + int64(ord(s[i]) - ord('0'))
    inc i
  if neg: return -v
  return v

proc parseU64(s: string): uint64 =
  var i = 0
  var v: uint64 = 0
  while i < s.len and s[i] >= '0' and s[i] <= '9':
    v = v * 10'u64 + uint64(ord(s[i]) - ord('0'))
    inc i
  return v

proc genIntLit(a: string): string =
  if a == "-9223372036854775808": return "(-9223372036854775807LL - 1LL)"
  let v = parseI64(a)
  if v >= -2147483648'i64 and v <= 2147483647'i64: return $v
  return $v & "LL"

proc genUIntLit(a: string): string =
  var n = a.len
  while n > 0 and (a[n-1] == 'l' or a[n-1] == 'L'): dec n
  if n > 0 and (a[n-1] == 'u' or a[n-1] == 'U'): dec n
  let digits = a[0 ..< n]
  let v = parseU64(digits)
  if v <= 4294967295'u64: return $v & "u"
  return $v & "ull"

# ---------------------------------------------------------------------------
# name mangling (faithful port of lengc/mangler.nim mangleToC)
# ---------------------------------------------------------------------------
proc escapeChar(ch: char): string =
  const HEX = "0123456789ABCDEF"
  let nn = ord(ch)
  result = "X"
  result.add HEX[(nn shr 4) and 0xF]
  result.add HEX[nn and 0xF]
  result.add 'Q'

proc mangleToC(s: string): string =
  result = ""
  var i = 0
  while i < s.len:
    let c = s[i]
    if (c >= 'A' and c <= 'P') or (c >= 'R' and c <= 'Z') or
       (c >= 'a' and c <= 'z') or (c >= '0' and c <= '9'):
      result.add c
    elif c == 'Q': result.add "QQ"
    elif c == '_': result.add "Q_"
    elif c == '.': result.add "_"
    elif c == '[':
      if i + 1 < s.len and s[i+1] == ']':
        if i + 2 < s.len and s[i+2] == '=':
          result.add "putQ"
          i += 2
        else:
          result.add "getQ"
          i += 1
      else:
        result.add escapeChar(c)
    elif c == '=':
      if i + 1 < s.len and s[i+1] == '=':
        result.add "eqQ"
        inc i
      else:
        result.add "eQ"
    elif c == '<':
      if i + 1 < s.len and s[i+1] == '=':
        result.add "leQ"
        inc i
      else:
        result.add "ltQ"
    elif c == '>':
      if i + 1 < s.len and s[i+1] == '=':
        result.add "geQ"
        inc i
      else:
        result.add "gtQ"
    elif c == '$': result.add "dollarQ"
    elif c == '%': result.add "percentQ"
    elif c == '&': result.add "ampQ"
    elif c == '^': result.add "roofQ"
    elif c == '!': result.add "emarkQ"
    elif c == '?': result.add "qmarkQ"
    elif c == '*': result.add "starQ"
    elif c == '+': result.add "plusQ"
    elif c == '-': result.add "minusQ"
    elif c == '/': result.add "slashQ"
    elif c == '\\': result.add "bslashQ"
    elif c == '~': result.add "tildeQ"
    elif c == ':': result.add "colonQ"
    elif c == '@': result.add "atQ"
    elif c == '|': result.add "barQ"
    else: result.add escapeChar(c)
    inc i

proc makeCString(s: string): string =
  result = "\""
  for ch in s:
    let code = ord(ch)
    if (code >= 0 and code <= 0x1F) or code >= 0x7F:
      result.add "\\"
      result.add toOctal(code)
    elif ch == '\'' or ch == '"' or ch == '\\' or ch == '?':
      result.add "\\"
      result.add ch
    else:
      result.add ch
  result.add "\""

proc toCCharLit(code: int): string =
  if (code >= 0 and code <= 0x1F) or code >= 0x7F:
    return "'\\" & toOctal(code) & "'"
  let ch = chr(code)
  if ch == '\'' or ch == '"' or ch == '\\' or ch == '?':
    return "'\\" & ch & "'"
  return "'" & ch & "'"

# ---------------------------------------------------------------------------
# operator tables
# ---------------------------------------------------------------------------
proc typedBinOp(t: string): string =
  if t == "add": return " + "
  elif t == "sub": return " - "
  elif t == "mul": return " * "
  elif t == "div": return " / "
  elif t == "mod": return " % "
  elif t == "shl": return " << "
  elif t == "shr": return " >> "
  elif t == "ashr": return " >> "
  elif t == "bitand": return " & "
  elif t == "bitor": return " | "
  elif t == "bitxor": return " ^ "
  return ""

proc cmpBinOp(t: string): string =
  if t == "eq": return " == "
  elif t == "neq": return " != "
  elif t == "le": return " <= "
  elif t == "lt": return " < "
  elif t == "ge": return " >= "
  elif t == "gt": return " > "
  elif t == "and": return " && "
  elif t == "or": return " || "
  return ""

proc suffixType(s: string): string =
  if s == "i64": return "NI64"
  elif s == "i32": return "NI32"
  elif s == "i16": return "NI16"
  elif s == "i8": return "NI8"
  elif s == "u64": return "NU64"
  elif s == "u32": return "NU32"
  elif s == "u16": return "NU16"
  elif s == "u8": return "NU8"
  elif s == "f64": return "NF64"
  elif s == "f32": return "NF32"
  elif s == "f": return "NF64"
  return "NI64"

# ---------------------------------------------------------------------------
# global emitter state (parallel seqs; reset per module)
# ---------------------------------------------------------------------------
var externKeys: seq[string] = @[]
var externVals: seq[string] = @[]
var typeExternKeys: seq[string] = @[]
var typeExternVals: seq[string] = @[]
var noDeclTypes: seq[string] = @[]

# cross-module resolution state: sibling `.c.nif` modules loaded on demand so we
# can emit correct `extern` prototypes / type declarations for foreign symbols.
var ownMod: string = ""
var loadedMods: seq[string] = @[]
var siblingSuffixes: seq[string] = @[]      # module basenames present in the dir
var siblingSuffixesLoaded = false
var modProcKeys: seq[string] = @[]
var modProcVals: seq[Node] = @[]
var modGlobalKeys: seq[string] = @[]
var modGlobalVals: seq[Node] = @[]
var modTypeKeys: seq[string] = @[]
var modTypeVals: seq[Node] = @[]

proc resetEmitter() =
  externKeys = @[]
  externVals = @[]
  typeExternKeys = @[]
  typeExternVals = @[]
  noDeclTypes = @[]
  ownMod = prog.main.name
  loadedMods = @[]
  siblingSuffixes = @[]
  siblingSuffixesLoaded = false
  modProcKeys = @[]
  modProcVals = @[]
  modGlobalKeys = @[]
  modGlobalVals = @[]
  modTypeKeys = @[]
  modTypeVals = @[]

proc mapHas(keys: seq[string]; k: string): bool =
  for x in keys:
    if x == k: return true
  return false

proc mapGet(keys, vals: seq[string]; k: string): string =
  for i in 0 ..< keys.len:
    if keys[i] == k: return vals[i]
  return ""

proc symName(name: string): string =
  if mapHas(externKeys, name): return mapGet(externKeys, externVals, name)
  return mangleToC(name)

proc typeName(name: string): string =
  if mapHas(typeExternKeys, name): return mapGet(typeExternKeys, typeExternVals, name)
  return mangleToC(name)

# ---------------------------------------------------------------------------
# pragma helpers
# ---------------------------------------------------------------------------
proc externName(pragmas: Node): string =
  if not isList(pragmas) or pragmas.tag != "pragmas": return ""
  for p in pragmas.kids:
    if isList(p) and (p.tag == "importc" or p.tag == "exportc" or p.tag == "importcpp"):
      if p.kids.len > 0:
        let s = p.kids[0]
        if s != nil and s.kind == nkStr: return s.strVal
        if isAtom(s): return s.atom
      return ""
  return ""

proc hasPragma(pragmas: Node; names: openArray[string]): bool =
  if not isList(pragmas) or pragmas.tag != "pragmas": return false
  for p in pragmas.kids:
    if isList(p) and oneOf(p.tag, names): return true
  return false

# ---------------------------------------------------------------------------
# forward declarations for the mutually-recursive emitters
# ---------------------------------------------------------------------------
proc genExpr(e: Node): string
proc genType(t: Node): string
proc genStmt(s: Node): string
proc genConstr(e: Node): string
proc buildNode(c: var Cursor): Node
proc procSignature(p: Node): string
proc genTypeDecl(td: Node): string
proc declare(t: Node; name: string): string

proc findTag(n: Node; tag: string): Node =
  if not isList(n): return nil
  for k in n.kids:
    if isList(k) and k.tag == tag: return k
  return nil

proc indexOfKid(n: Node; target: Node): int =
  for i in 0 ..< n.kids.len:
    if n.kids[i] == target: return i
  return -1

proc paramType(paramNode: Node): Node =
  # (param name pragmas type [default])
  var i = 1
  while i < paramNode.kids.len:
    let k = paramNode.kids[i]
    if isList(k) or (isAtom(k) and k.atom != "." and not k.def): return k
    inc i
  return paramNode.kids[2]

# ---------------------------------------------------------------------------
# types
# ---------------------------------------------------------------------------
proc bitsOf(t: Node): string =
  if t.kids.len == 0: return ""
  let last = t.kids[t.kids.len - 1]
  if isAtom(last) and isIntLit(last.atom):
    if last.atom == "-1": return ""
    return last.atom
  return ""

proc genProcTypePtr(t: Node): string =
  let params = findTag(t, "params")
  var ret: Node = nil
  if params != nil:
    let idx = indexOfKid(t, params)
    if idx >= 0 and idx + 1 < t.kids.len: ret = t.kids[idx + 1]
  else:
    if t.kids.len > 0: ret = t.kids[t.kids.len - 1]
  var args: seq[string] = @[]
  if params != nil:
    for k in params.kids:
      if isList(k) and k.tag == "param": args.add genType(paramType(k))
  let argStr = if args.len > 0: joinSeq(args, ", ") else: "void"
  return genType(ret) & "(*)(" & argStr & ")"

proc genType(t: Node): string =
  if isDot(t): return "void"
  if isAtom(t):
    if t.atom == "void": return "void"
    return typeName(t.atom)
  if not isList(t):
    fail("aowlc: bad type node")
    return ""
  let tg = t.tag
  if tg == "i": return "NI" & bitsOf(t)
  elif tg == "u": return "NU" & bitsOf(t)
  elif tg == "f": return "NF" & bitsOf(t)
  elif tg == "c": return "NC" & bitsOf(t)
  elif tg == "bool": return "NB8"
  elif tg == "void": return "void"
  elif tg == "ptr" or tg == "aptr": return genType(t.kids[0]) & "*"
  elif tg == "flexarray": return genType(t.kids[0]) & "*"
  elif tg == "proctype": return genProcTypePtr(t)
  elif tg == "array": return genType(t.kids[0]) & "*"
  else:
    if t.kids.len > 0: return genType(t.kids[0])
    fail("aowlc: unsupported type '" & tg & "'")
    return ""

proc declare(t: Node; name: string): string =
  if isList(t) and t.tag == "array":
    let size = t.kids[t.kids.len - 1]
    let len2 = if isAtom(size): size.atom else: "0"
    return genType(t.kids[0]) & " " & name & "[" & len2 & "]"
  if isList(t) and t.tag == "flexarray":
    return genType(t.kids[0]) & " " & name & "[]"
  if isList(t) and t.tag == "proctype":
    let params = findTag(t, "params")
    var ret: Node = nil
    if params != nil:
      let idx = indexOfKid(t, params)
      if idx >= 0 and idx + 1 < t.kids.len: ret = t.kids[idx + 1]
    else:
      if t.kids.len > 0: ret = t.kids[t.kids.len - 1]
    var args: seq[string] = @[]
    if params != nil:
      for k in params.kids:
        if isList(k) and k.tag == "param": args.add genType(paramType(k))
    let argStr = if args.len > 0: joinSeq(args, ", ") else: "void"
    return genType(ret) & " (*" & name & ")(" & argStr & ")"
  return genType(t) & " " & name

# ---------------------------------------------------------------------------
# expressions
# ---------------------------------------------------------------------------
proc genConstr(e: Node): string =
  if e.tag == "aconstr":
    var vals: seq[string] = @[]
    var i = 1
    while i < e.kids.len:
      vals.add genExpr(e.kids[i])
      inc i
    if isAtom(e.kids[0]):
      return "(" & genType(e.kids[0]) & "){ .a = { " & joinSeq(vals, ", ") & " } }"
    return "{ " & joinSeq(vals, ", ") & " }"
  let ty = genType(e.kids[0])
  var parts: seq[string] = @[]
  var i = 1
  while i < e.kids.len:
    let kv = e.kids[i]
    if isList(kv) and kv.tag == "kv":
      let fld = kv.kids[0]
      let fname = if isAtom(fld): mangleToC(fld.atom) else: genExpr(fld)
      var inh = ""
      if kv.kids.len > 2 and isAtom(kv.kids[2]) and isIntLit(kv.kids[2].atom):
        inh = myRepeat(".Q", parseI64(kv.kids[2].atom).int)
      parts.add inh & "." & fname & " = " & genExpr(kv.kids[1])
    else:
      parts.add genExpr(kv)
    inc i
  return "(" & ty & "){ " & joinSeq(parts, ", ") & " }"

proc genExpr(e: Node): string =
  if e == nil: return ""
  if e.kind == nkStr: return makeCString(e.strVal)
  if e.kind == nkChar: return "(NC8)" & toCCharLit(e.chrVal)
  if isAtom(e):
    let a = e.atom
    if a == "true": return "NIM_TRUE"
    if a == "false": return "NIM_FALSE"
    if a == "nil": return "NIM_NIL"
    if a == "inf": return "INF"
    if a == "neginf": return "-INF"
    if a == "nan": return "NAN"
    if isUIntLit(a): return genUIntLit(a)
    if isIntLit(a): return genIntLit(a)
    if isFloatLit(a): return a
    return symName(a)
  if not isList(e):
    fail("aowlc: bad expr node")
    return ""
  let t = e.tag
  let tb = typedBinOp(t)
  if tb.len > 0:
    let ty = genType(e.kids[0])
    let a = e.kids[e.kids.len - 2]
    let b = e.kids[e.kids.len - 1]
    return "((" & ty & ")(" & genExpr(a) & tb & genExpr(b) & "))"
  let cb = cmpBinOp(t)
  if cb.len > 0:
    let a = e.kids[e.kids.len - 2]
    let b = e.kids[e.kids.len - 1]
    return "(" & genExpr(a) & cb & genExpr(b) & ")"
  if t == "neg":
    return "((" & genType(e.kids[0]) & ")-" & genExpr(e.kids[e.kids.len - 1]) & ")"
  elif t == "bitnot":
    return "((" & genType(e.kids[0]) & ")~" & genExpr(e.kids[e.kids.len - 1]) & ")"
  elif t == "not":
    return "(!" & genExpr(e.kids[e.kids.len - 1]) & ")"
  elif t == "cast" or t == "conv" or t == "hconv":
    return "((" & genType(e.kids[0]) & ")" & genExpr(e.kids[e.kids.len - 1]) & ")"
  elif t == "baseobj":
    let expr = genExpr(e.kids[e.kids.len - 1])
    var level = 1
    if e.kids.len >= 3 and isAtom(e.kids[1]) and isIntLit(e.kids[1].atom):
      level = parseI64(e.kids[1].atom).int
    return "(" & expr & myRepeat(".Q", level) & ")"
  elif t == "call" or t == "hcall" or t == "onerr":
    var start = 1
    if t == "onerr": start = 2
    let fn = genExpr(e.kids[start - 1])
    var args: seq[string] = @[]
    var i = start
    while i < e.kids.len:
      args.add genExpr(e.kids[i])
      inc i
    return fn & "(" & joinSeq(args, ", ") & ")"
  elif t == "suf":
    let val = e.kids[0]
    let suf = e.kids[1]
    if val != nil and val.kind == nkStr: return genExpr(val)
    let sname = if isAtom(suf): suf.atom elif (suf != nil and suf.kind == nkStr): suf.strVal else: ""
    let ty = suffixType(sname)
    return "((" & ty & ")" & genExpr(val) & ")"
  elif t == "paren" or t == "expr":
    return "(" & genExpr(e.kids[e.kids.len - 1]) & ")"
  elif t == "addr":
    return "(&" & genExpr(e.kids[0]) & ")"
  elif t == "deref" or t == "hderef":
    return "(*" & genExpr(e.kids[0]) & ")"
  elif t == "at":
    return genExpr(e.kids[0]) & ".a[" & genExpr(e.kids[1]) & "]"
  elif t == "pat":
    return genExpr(e.kids[0]) & "[" & genExpr(e.kids[1]) & "]"
  elif t == "dot":
    let obj = genExpr(e.kids[0])
    let fld = e.kids[1]
    var inh = ""
    if e.kids.len > 2 and isAtom(e.kids[2]) and isIntLit(e.kids[2].atom):
      inh = myRepeat(".Q", parseI64(e.kids[2].atom).int)
    let fname = if isAtom(fld): mangleToC(fld.atom) else: genExpr(fld)
    return obj & inh & "." & fname
  elif t == "sizeof":
    return "sizeof(" & genType(e.kids[0]) & ")"
  elif t == "alignof":
    return "NIM_ALIGNOF(" & genType(e.kids[0]) & ")"
  elif t == "true": return "NIM_TRUE"
  elif t == "false": return "NIM_FALSE"
  elif t == "nil": return "NIM_NIL"
  elif t == "inf": return "INF"
  elif t == "neginf": return "-INF"
  elif t == "nan": return "NAN"
  elif t == "oconstr" or t == "aconstr": return genConstr(e)
  elif t == "ovf": return "LENGC_OVF_"
  else:
    fail("aowlc: unsupported expr '" & t & "'")
    return ""

# ---------------------------------------------------------------------------
# statements
# ---------------------------------------------------------------------------
proc genLvalue(n: Node): string =
  if isAtom(n): return symName(n.atom)
  return genExpr(n)

proc condExpr(n: Node): string =
  if isList(n) and cmpBinOp(n.tag).len > 0:
    let a = n.kids[n.kids.len - 2]
    let b = n.kids[n.kids.len - 1]
    return genExpr(a) & cmpBinOp(n.tag) & genExpr(b)
  return genExpr(n)

proc declName(name: string; pragmas: Node): string =
  let ext = externName(pragmas)
  if ext.len > 0: return ext
  if isList(pragmas) and hasPragma(pragmas, ["importc", "exportc", "importcpp"]):
    return beforeDot(name)
  return mangleToC(name)

proc genLocalVar(s: Node): string =
  let nameAtom = s.kids[0]
  let pragmas = s.kids[1]
  var typ = s.kids[2]
  let value = if s.kids.len > 3: s.kids[3] else: nil
  let isConst = s.tag == "const"
  let nm = if isAtom(nameAtom): declName(nameAtom.atom, pragmas) else: "v"
  if isDot(typ): typ = nil
  let hasInit = value != nil and not isDot(value)
  var decl = if typ != nil: declare(typ, nm) else: "NI " & nm
  if isConst: decl = "static const " & decl
  return decl & (if hasInit: " = " & genExpr(value) else: "") & ";"

proc genIf(s: Node): string =
  var outp = ""
  var firstElif = true
  for br in s.kids:
    if not isList(br): continue
    if br.tag == "elif":
      outp.add (if firstElif: "if (" else: " else if (") & condExpr(br.kids[0]) & ") {\n" &
        genStmt(br.kids[1]) & "\n}"
      firstElif = false
    elif br.tag == "else":
      outp.add " else {\n" & genStmt(br.kids[0]) & "\n}"
  return outp

proc genCase(s: Node): string =
  var outp = "switch (" & condExpr(s.kids[0]) & ") {\n"
  var i = 1
  while i < s.kids.len:
    let br = s.kids[i]
    inc i
    if not isList(br): continue
    if br.tag == "of":
      let ranges = br.kids[0]
      let body = br.kids[1]
      var labels: seq[string] = @[]
      var vals: seq[Node] = @[]
      if isList(ranges) and ranges.tag == "ranges":
        for k in ranges.kids: vals.add k
      else:
        vals.add ranges
      for v in vals:
        if isList(v) and v.tag == "range":
          labels.add "case " & genExpr(v.kids[0]) & " ... " & genExpr(v.kids[1]) & ":"
        else:
          labels.add "case " & genExpr(v) & ":"
      outp.add joinSeq(labels, "\n") & " {\n" & genStmt(body) & "\nbreak;\n}\n"
    elif br.tag == "else":
      outp.add "default: {\n" & genStmt(br.kids[0]) & "\nbreak;\n}\n"
  return outp & "}"

proc genKeepOverflow(s: Node): string =
  let op = s.kids[0]
  let lval = s.kids[1]
  var builtin = ""
  if op.tag == "add": builtin = "__builtin_add_overflow"
  elif op.tag == "sub": builtin = "__builtin_sub_overflow"
  elif op.tag == "mul": builtin = "__builtin_mul_overflow"
  if builtin.len == 0:
    fail("aowlc: unsupported keepovf op '" & op.tag & "'")
    return ""
  let a = op.kids[op.kids.len - 2]
  let b = op.kids[op.kids.len - 1]
  return "if (" & builtin & "(" & genExpr(a) & ", " & genExpr(b) & ", &" &
    genLvalue(lval) & ")) { LENGC_OVF_ = LENGC_OVF_ || NIM_TRUE; }"

proc genStmt(s: Node): string =
  if isDot(s): return ""
  if not isList(s): return ""
  let t = s.tag
  if t == "stmts":
    var parts: seq[string] = @[]
    for k in s.kids:
      let c = genStmt(k)
      if c.len > 0: parts.add c
    return joinSeq(parts, "\n")
  elif t == "scope":
    var parts: seq[string] = @[]
    for k in s.kids:
      let c = genStmt(k)
      if c.len > 0: parts.add c
    return "{\n" & joinSeq(parts, "\n") & "\n}"
  elif t == "var" or t == "let" or t == "cursor" or t == "const" or
       t == "gvar" or t == "glet" or t == "tvar":
    return genLocalVar(s)
  elif t == "asgn":
    return genLvalue(s.kids[0]) & " = " & genExpr(s.kids[1]) & ";"
  elif t == "store":
    return genLvalue(s.kids[1]) & " = " & genExpr(s.kids[0]) & ";"
  elif t == "ret":
    if s.kids.len == 0 or isDot(s.kids[0]): return "return;"
    return "return " & genExpr(s.kids[0]) & ";"
  elif t == "if":
    return genIf(s)
  elif t == "while":
    return "while (" & condExpr(s.kids[0]) & ") {\n" & genStmt(s.kids[1]) & "\n}"
  elif t == "loop":
    let pre = genStmt(s.kids[0])
    let cond = genExpr(s.kids[1])
    let body = genStmt(s.kids[2])
    return "while (NIM_TRUE) {\n" & pre & "\nif (!(" & cond & ")) break;\n" & body & "\n}"
  elif t == "break": return "break;"
  elif t == "continue": return "continue;"
  elif t == "call" or t == "hcall": return genExpr(s) & ";"
  elif t == "onerr": return genExpr(s) & ";"
  elif t == "discard": return "(void)(" & genExpr(s.kids[0]) & ");"
  elif t == "lab":
    let nm = if isAtom(s.kids[0]): mangleToC(s.kids[0].atom) else: "L"
    return nm & ": ;"
  elif t == "jmp":
    let nm = if isAtom(s.kids[0]): mangleToC(s.kids[0].atom) else: "L"
    return "goto " & nm & ";"
  elif t == "case":
    return genCase(s)
  elif t == "keepovf":
    return genKeepOverflow(s)
  elif t == "raise":
    return "/* raise */ (void)0;"
  elif t == "pragmas" or t == "comment" or t == "emit" or t == "smry":
    return ""
  else:
    fail("aowlc: unsupported stmt '" & t & "'")
    return ""

# ---------------------------------------------------------------------------
# procs
# ---------------------------------------------------------------------------
type
  ProcParts = object
    nameAtom: Node
    params: Node
    ret: Node
    body: Node
    pragmas: Node
    pnodes: seq[Node]

proc procParts(p: Node): ProcParts =
  result = default(ProcParts)
  result.nameAtom = p.kids[0]
  result.params = findTag(p, "params")
  result.ret = nil
  if result.params != nil:
    let pi = indexOfKid(p, result.params)
    if pi + 1 < p.kids.len: result.ret = p.kids[pi + 1]
  else:
    if p.kids.len > 1: result.ret = p.kids[1]
  result.body = nil
  var j = p.kids.len - 1
  while j >= 0:
    if isList(p.kids[j]) and p.kids[j].tag == "stmts":
      result.body = p.kids[j]
      break
    dec j
  result.pragmas = findTag(p, "pragmas")
  result.pnodes = @[]
  if result.params != nil:
    for k in result.params.kids:
      if isList(k) and k.tag == "param": result.pnodes.add k

proc procSignature(p: Node): string =
  let pp = procParts(p)
  let name = declName(pp.nameAtom.atom, pp.pragmas)
  let retC = if pp.ret == nil or isDot(pp.ret): "void" else: genType(pp.ret)
  var args: seq[string] = @[]
  for pn in pp.pnodes:
    let nameNode = pn.kids[0]
    let pt = paramType(pn)
    if isList(pt) and pt.tag == "varargs":
      args.add "..."
    else:
      args.add declare(pt, mangleToC(nameNode.atom))
  var prefix = ""
  if pp.pragmas != nil and hasPragma(pp.pragmas, ["inline"]): prefix = "static inline "
  let argStr = if args.len > 0: joinSeq(args, ", ") else: "void"
  return prefix & retC & " " & name & "(" & argStr & ")"

proc genProc(p: Node): string =
  let pp = procParts(p)
  let sig = procSignature(p)
  if pp.body == nil: return sig & ";"
  return sig & " {\n" & genStmt(pp.body) & "\n}"

# ---------------------------------------------------------------------------
# literal-node check (for deciding inline global initializers)
# ---------------------------------------------------------------------------
proc isLiteralNode(v: Node): bool =
  if v == nil: return false
  if v.kind == nkStr or v.kind == nkChar: return true
  if isAtom(v):
    let a = v.atom
    return a == "." or a == "true" or a == "false" or a == "nil" or
      isIntLit(a) or isUIntLit(a) or isFloatLit(a)
  if isList(v):
    if oneOf(v.tag, ["suf", "true", "false", "nil", "inf", "neginf", "nan", "cast", "conv"]):
      return true
    if v.tag == "aconstr" or v.tag == "oconstr":
      var i = 1
      while i < v.kids.len:
        let k = v.kids[i]
        if isList(k) and k.tag == "kv":
          if not isLiteralNode(k.kids[1]): return false
        else:
          if not isLiteralNode(k): return false
        inc i
      return true
  return false

# ---------------------------------------------------------------------------
# globals
# ---------------------------------------------------------------------------
type
  GlobalInfo = object
    name: string
    decl: string
    nameAtom: string
    needsInit: bool
    value: Node

proc genGlobal(g: Node): GlobalInfo =
  let nameAtom = g.kids[0]
  let pragmas = g.kids[1]
  let typ = g.kids[2]
  let value = if g.kids.len > 3: g.kids[3] else: nil
  let nm = declName(nameAtom.atom, pragmas)
  let isConst = g.tag == "const"
  var decl = declare(typ, nm)
  if isConst: decl = "static const " & decl
  let hasInit = value != nil and not isDot(value) and isLiteralNode(value)
  result = default(GlobalInfo)
  result.name = nm
  result.decl = decl & (if hasInit: " = " & genExpr(value) else: "") & ";"
  result.nameAtom = nameAtom.atom
  result.needsInit = value != nil and not isDot(value) and not hasInit
  result.value = value

# ---------------------------------------------------------------------------
# type declarations
# ---------------------------------------------------------------------------
proc genObjectFields(body: Node): string =
  var fields = ""
  var start = 0
  if body.kids.len > 0 and (isDot(body.kids[0]) or isAtom(body.kids[0])):
    if isAtom(body.kids[0]) and not isDot(body.kids[0]):
      fields.add typeName(body.kids[0].atom) & " Q;\n"
    start = 1
  var i = start
  while i < body.kids.len:
    let f = body.kids[i]
    inc i
    if not isList(f): continue
    if f.tag == "fld":
      let fn = f.kids[0]
      let ftype = f.kids[f.kids.len - 1]
      fields.add declare(ftype, mangleToC(fn.atom)) & ";\n"
    elif f.tag == "union":
      fields.add "union {\n"
      for branch in f.kids:
        if isList(branch) and branch.tag == "object":
          fields.add "struct {\n" & genObjectFields(branch) & "};\n"
      fields.add "};\n"
  return fields

proc genObjectDecl(nm: string; body: Node; isUnion: bool): string =
  let kw = if isUnion: "typedef union " else: "typedef struct "
  return kw & nm & " {\n" & genObjectFields(body) & "} " & nm & ";"

proc genEnumDecl(nm: string; body: Node): string =
  let base = body.kids[0]
  var outp = "typedef " & genType(base) & " " & nm & ";\n"
  var i = 1
  while i < body.kids.len:
    let ef = body.kids[i]
    inc i
    if isList(ef) and ef.tag == "efld":
      let en = ef.kids[0]
      let ev = ef.kids[1]
      outp.add "#define " & mangleToC(en.atom) & " ((" & genType(base) & ")" & genExpr(ev) & ")\n"
  return outp

proc genTypeDecl(td: Node): string =
  let nameAtom = td.kids[0]
  let pragmas = findTag(td, "pragmas")
  let body = td.kids[td.kids.len - 1]
  if hasPragma(pragmas, ["nodecl", "importc", "importcpp", "header"]): return ""
  let nm = mangleToC(nameAtom.atom)
  if isList(body):
    if body.tag == "object" or body.tag == "union":
      return genObjectDecl(nm, body, body.tag == "union")
    if body.tag == "enum":
      return genEnumDecl(nm, body)
    if body.tag == "array":
      let size = body.kids[body.kids.len - 1]
      let len2 = if isAtom(size): size.atom else: "0"
      return "typedef struct " & nm & " { " & genType(body.kids[0]) & " a[" & len2 & "]; } " & nm & ";"
    if body.tag == "proctype":
      return "typedef " & declare(body, nm) & ";"
    if oneOf(body.tag, ["i", "u", "f", "c", "bool", "ptr", "aptr"]):
      return "typedef " & declare(body, nm) & ";"
  if isAtom(body):
    return "typedef " & typeName(body.atom) & " " & nm & ";"
  return ""

# ---------------------------------------------------------------------------
# module classification / whole-program emit
# ---------------------------------------------------------------------------
# No-header importc runtime symbols backed by libc (mimalloc allocator), so a
# linked program is self-contained. Faithful to aowlc.js RUNTIME_PROVISIONS.
proc provisionImpl(name: string): string =
  # `static`: each module that imports one of these runtime symbols emits its own
  # libc-backed definition, so give them internal linkage to avoid clashes at link.
  if name == "mi_malloc": return "static void* mi_malloc(NU n) { return malloc((size_t)n); }"
  elif name == "mi_free": return "static void mi_free(void* p) { free(p); }"
  elif name == "mi_realloc": return "static void* mi_realloc(void* p, NU n) { return realloc(p, (size_t)n); }"
  elif name == "mi_usable_size": return "static NU mi_usable_size(void* p) { return (NU)malloc_usable_size(p); }"
  return ""

proc provisionNeeds(name: string): string =
  if name == "mi_usable_size": return "<malloc.h>"
  elif name == "mi_malloc" or name == "mi_free" or name == "mi_realloc": return "<stdlib.h>"
  return ""

proc isProvision(name: string): bool = provisionImpl(name).len > 0

proc addHeaders(pragmas: Node; headers: var seq[string]) =
  if not isList(pragmas): return
  for pr in pragmas.kids:
    if isList(pr) and pr.tag == "header" and pr.kids.len > 0 and
       pr.kids[0] != nil and pr.kids[0].kind == nkStr:
      if not mapHas(headers, pr.kids[0].strVal): headers.add pr.kids[0].strVal

proc isStmtTag(t: string): bool =
  oneOf(t, ["asgn", "store", "call", "hcall", "if", "while", "loop", "case",
    "scope", "lab", "jmp", "discard", "onerr", "keepovf", "raise", "ret", "break"])

type
  Classified = object
    procs: seq[Node]
    globals: seq[Node]
    types: seq[Node]
    topStmts: seq[Node]

proc classify(root: Node): Classified =
  # root IS the top-level (stmts …) node
  if not (isList(root) and root.tag == "stmts"):
    fail("aowlc: no top-level (stmts …) found — is this a .c.nif?")
  result = default(Classified)
  result.procs = @[]
  result.globals = @[]
  result.types = @[]
  result.topStmts = @[]
  for d in root.kids:
    if not isList(d): continue
    if d.tag == "proc" or d.tag == "func": result.procs.add d
    elif oneOf(d.tag, ["gvar", "tvar", "glet", "var", "const", "let"]): result.globals.add d
    elif d.tag == "type": result.types.add d
    elif isStmtTag(d.tag): result.topStmts.add d

proc buildExternMaps(procs, globals, types: seq[Node]) =
  for p in procs:
    let pp = procParts(p)
    let ext = externName(pp.pragmas)
    if ext.len > 0:
      externKeys.add pp.nameAtom.atom
      externVals.add ext
    elif hasPragma(pp.pragmas, ["importc", "exportc", "importcpp"]):
      externKeys.add pp.nameAtom.atom
      externVals.add beforeDot(pp.nameAtom.atom)
  for g in globals:
    let nameAtom = g.kids[0]
    let pragmas = g.kids[1]
    let ext = externName(pragmas)
    if ext.len > 0:
      externKeys.add nameAtom.atom
      externVals.add ext
  for td in types:
    let nameAtom = td.kids[0]
    let pragmas = findTag(td, "pragmas")
    let ext = externName(pragmas)
    if ext.len > 0:
      typeExternKeys.add nameAtom.atom
      typeExternVals.add ext
    if hasPragma(pragmas, ["nodecl", "importc", "importcpp", "header"]):
      noDeclTypes.add nameAtom.atom

proc collectCalls(node: Node; outp: var seq[string]) =
  if node == nil: return
  if isList(node):
    if (node.tag == "call" or node.tag == "hcall") and node.kids.len > 0 and isAtom(node.kids[0]):
      if not mapHas(outp, node.kids[0].atom): outp.add node.kids[0].atom
    if node.tag == "onerr" and node.kids.len > 1 and isAtom(node.kids[1]):
      if not mapHas(outp, node.kids[1].atom): outp.add node.kids[1].atom
    for k in node.kids: collectCalls(k, outp)

# value-type dependency ordering for struct decls
proc collectValueTypeAtoms(node: Node; outp: var seq[string]) =
  if node == nil: return
  if isAtom(node):
    if not isDot(node):
      if not mapHas(outp, node.atom): outp.add node.atom
    return
  if not isList(node): return
  let tg = node.tag
  if tg == "ptr" or tg == "aptr" or tg == "flexarray": return
  elif tg == "array":
    collectValueTypeAtoms(node.kids[0], outp)
    return
  elif tg == "object" or tg == "union":
    var start = 0
    if node.kids.len > 0 and (isDot(node.kids[0]) or isAtom(node.kids[0])):
      if isAtom(node.kids[0]) and not isDot(node.kids[0]):
        if not mapHas(outp, node.kids[0].atom): outp.add node.kids[0].atom
      start = 1
    var i = start
    while i < node.kids.len:
      let f = node.kids[i]
      inc i
      if not isList(f): continue
      if f.tag == "fld": collectValueTypeAtoms(f.kids[f.kids.len - 1], outp)
      elif f.tag == "union" or f.tag == "object": collectValueTypeAtoms(f, outp)
    return
  else:
    return

# orderTypesByValueDeps state (module-level; nimony has no easy closures)
var otNames: seq[string] = @[]
var otTypes: seq[Node] = @[]
var otOrder: seq[Node] = @[]
var otStateKeys: seq[string] = @[]
var otStateVals: seq[int] = @[]

proc otStateOf(nm: string): int =
  for i in 0 ..< otStateKeys.len:
    if otStateKeys[i] == nm: return otStateVals[i]
  return -1

proc otSetState(nm: string; v: int) =
  for i in 0 ..< otStateKeys.len:
    if otStateKeys[i] == nm:
      otStateVals[i] = v
      return
  otStateKeys.add nm
  otStateVals.add v

proc otByName(nm: string): Node =
  for i in 0 ..< otTypes.len:
    if otNames[i] == nm: return otTypes[i]
  return nil

proc otValueDeps(td: Node): seq[string] =
  result = @[]
  let pragmas = findTag(td, "pragmas")
  if hasPragma(pragmas, ["nodecl", "importc", "importcpp", "header"]): return
  var deps: seq[string] = @[]
  collectValueTypeAtoms(td.kids[td.kids.len - 1], deps)
  for d in deps:
    if mapHas(otNames, d) and not mapHas(result, d): result.add d

proc otVisit(td: Node) =
  let nm = td.kids[0].atom
  if otStateOf(nm) >= 0: return
  otSetState(nm, 0)
  for d in otValueDeps(td):
    let dtd = otByName(d)
    if dtd != nil and dtd != td: otVisit(dtd)
  otSetState(nm, 1)
  otOrder.add td

proc orderTypesByValueDeps(types: seq[Node]): seq[Node] =
  otNames = @[]
  otTypes = types
  otOrder = @[]
  otStateKeys = @[]
  otStateVals = @[]
  for td in types: otNames.add td.kids[0].atom
  for td in types: otVisit(td)
  return otOrder

# ---------------------------------------------------------------------------
# cross-module symbol resolution
# ---------------------------------------------------------------------------
proc lastComponent(s: string): string =
  var i = s.len - 1
  while i >= 0 and s[i] != '.': dec i
  if i < 0: return ""          # no dot at all → not a qualified symbol
  return s[i + 1 ..< s.len]

# returns the owning module suffix if `atom` is a symbol defined in a sibling
# module (its trailing dotted component names a sibling `.c.nif`), else "".
# Results are cached: `siblingSuffixes` = known-good, `checkedSuffixes` = probed.
var checkedSuffixes: seq[string] = @[]
proc foreignModuleOf(atom: string): string =
  let lc = lastComponent(atom)
  if lc.len == 0: return ""
  if lc == ownMod: return ""
  if mapHas(siblingSuffixes, lc): return lc
  if mapHas(checkedSuffixes, lc): return ""
  checkedSuffixes.add lc
  let dir = if prog.main.dir.len > 0: prog.main.dir else: "."
  if fileExists(dir & "/" & lc & ".c.nif"):
    siblingSuffixes.add lc
    return lc
  return ""

proc loadSiblingModule(suffix: string) =
  if mapHas(loadedMods, suffix): return
  loadedMods.add suffix
  let dir = if prog.main.dir.len > 0: prog.main.dir else: "."
  let path = dir & "/" & suffix & ".c.nif"
  if not fileExists(path): return
  var buf = parseFromFile(path)
  var cur = beginRead(buf)
  let tree = buildNode(cur)
  endRead buf
  if not isList(tree): return
  for d in tree.kids:
    if not isList(d): continue
    if d.tag == "proc" or d.tag == "func":
      if d.kids.len > 0 and isAtom(d.kids[0]):
        modProcKeys.add d.kids[0].atom
        modProcVals.add d
    elif oneOf(d.tag, ["gvar", "tvar", "glet", "var", "let", "const"]):
      if d.kids.len > 0 and isAtom(d.kids[0]):
        modGlobalKeys.add d.kids[0].atom
        modGlobalVals.add d
    elif d.tag == "type":
      if d.kids.len > 0 and isAtom(d.kids[0]):
        modTypeKeys.add d.kids[0].atom
        modTypeVals.add d

proc modFindProc(atom: string): Node =
  for i in 0 ..< modProcKeys.len:
    if modProcKeys[i] == atom: return modProcVals[i]
  return nil

proc modFindGlobal(atom: string): Node =
  for i in 0 ..< modGlobalKeys.len:
    if modGlobalKeys[i] == atom: return modGlobalVals[i]
  return nil

proc modFindType(atom: string): Node =
  for i in 0 ..< modTypeKeys.len:
    if modTypeKeys[i] == atom: return modTypeVals[i]
  return nil

# Recursively collect every atom in `n` that names a foreign-module symbol.
proc collectForeignAtoms(n: Node; outp: var seq[string]) =
  if n == nil: return
  if isAtom(n):
    if foreignModuleOf(n.atom).len > 0 and not mapHas(outp, n.atom): outp.add n.atom
    return
  if isList(n):
    # field names in a `dot`/`kv` are member accesses, not linkable symbols
    for k in n.kids: collectForeignAtoms(k, outp)

proc indentC(src: string): string =
  let lines = splitLinesNl(src)
  var depth = 0
  var outp: seq[string] = @[]
  for raw in lines:
    let line = stripBoth(raw)
    if line.len == 0:
      outp.add ""
      continue
    if line[0] == '#':
      outp.add line
      continue
    var d = depth
    if line[0] == '}':
      d = if depth - 1 > 0: depth - 1 else: 0
    outp.add myRepeat("  ", d) & line
    for ch in line:
      if ch == '{': inc depth
      elif ch == '}': depth = (if depth - 1 > 0: depth - 1 else: 0)
  return joinSeq(outp, "\n")

# Emit the module body (everything AFTER `PRELUDE + "\n"`), indentC-processed.
proc emitUnit(parts: Classified): string =
  let procs = parts.procs
  let globals = parts.globals
  let types = parts.types
  let topStmts = parts.topStmts

  buildExternMaps(procs, globals, types)

  var definedSyms: seq[string] = @[]
  for p in procs:
    let nm = procParts(p).nameAtom.atom
    if not mapHas(definedSyms, nm): definedSyms.add nm
  for g in globals:
    let nm = g.kids[0].atom
    if not mapHas(definedSyms, nm): definedSyms.add nm

  # ---- cross-module resolution -------------------------------------------
  # Collect every foreign-module symbol this module references, load the
  # defining sibling `.c.nif`, and materialise `extern` prototypes / type
  # declarations for them. A fixpoint is required because a foreign proc's
  # signature (or a foreign struct's fields) may pull in further foreign types.
  var foreignProcs: seq[Node] = @[]
  var foreignGlobals: seq[Node] = @[]
  var foreignTypes: seq[Node] = @[]
  var seenForeign: seq[string] = @[]
  var pending: seq[string] = @[]
  for p in procs: collectForeignAtoms(p, pending)
  for g in globals: collectForeignAtoms(g, pending)
  for td in types: collectForeignAtoms(td, pending)
  for s in topStmts: collectForeignAtoms(s, pending)
  var qi = 0
  while qi < pending.len:
    let atom = pending[qi]
    inc qi
    if mapHas(seenForeign, atom): continue
    seenForeign.add atom
    let m = foreignModuleOf(atom)
    if m.len == 0: continue
    loadSiblingModule(m)
    let pn = modFindProc(atom)
    if pn != nil:
      foreignProcs.add pn
      collectForeignAtoms(pn, pending)   # its signature may reference more
      continue
    let gn = modFindGlobal(atom)
    if gn != nil:
      foreignGlobals.add gn
      collectForeignAtoms(gn, pending)
      continue
    let tn = modFindType(atom)
    if tn != nil:
      foreignTypes.add tn
      collectForeignAtoms(tn, pending)
      continue
    # else: a member/field name or an unresolved symbol — ignored.

  # foreign importc names must be registered too, so typeName/symName map right.
  buildExternMaps(foreignProcs, foreignGlobals, foreignTypes)

  # all types needing a declaration in this TU: foreign first (deps), then local.
  var allTypes: seq[Node] = @[]
  for td in foreignTypes: allTypes.add td
  for td in types: allTypes.add td

  # forward declarations for object/union structs
  var fwdDecls: seq[string] = @[]
  for td in allTypes:
    let pragmas = findTag(td, "pragmas")
    if hasPragma(pragmas, ["nodecl", "importc", "importcpp", "header"]): continue
    let body = td.kids[td.kids.len - 1]
    if isList(body) and (body.tag == "object" or body.tag == "union"):
      let nm = mangleToC(td.kids[0].atom)
      let kw = if body.tag == "union": "union " else: "struct "
      fwdDecls.add "typedef " & kw & nm & " " & nm & ";"

  # type declarations (value-dependency ordered), foreign + local together
  var typeDecls: seq[string] = @[]
  let ordered = orderTypesByValueDeps(allTypes)
  for td in ordered:
    let s = genTypeDecl(td)
    if s.len > 0: typeDecls.add s

  # prototypes + definitions
  var protos: seq[string] = @[]
  var defs: seq[string] = @[]
  var provisionsNeeded: seq[string] = @[]
  for p in procs:
    let pp = procParts(p)
    if hasPragma(pp.pragmas, ["header", "nodecl"]): continue
    if hasPragma(pp.pragmas, ["importc", "importcpp"]):
      var ext = externName(pp.pragmas)
      if ext.len == 0: ext = beforeDot(pp.nameAtom.atom)
      if ext.len >= 2 and ext[0] == '_' and ext[1] == '_': continue
      if isProvision(ext):
        # emitted as a `static` libc-backed impl before any use; no proto needed.
        if not mapHas(provisionsNeeded, ext): provisionsNeeded.add ext
        continue
      protos.add procSignature(p) & ";"
      continue
    let sig = procSignature(p)
    if pp.body == nil:
      protos.add sig & ";"
      continue
    protos.add sig & ";"
    defs.add genProc(p)

  # extern prototypes / globals for foreign-module symbols (real cross-module
  # linkage — the defining module emits the definition, we just declare it).
  var stubs: seq[string] = @[]          # foreign prototypes + extern globals
  var foreignDefs: seq[string] = @[]    # foreign `static inline` definitions
  for pn in foreignProcs:
    let pp = procParts(pn)
    if hasPragma(pp.pragmas, ["header", "nodecl"]): continue
    if hasPragma(pp.pragmas, ["importc", "importcpp"]):
      var ext = externName(pp.pragmas)
      if ext.len == 0: ext = beforeDot(pp.nameAtom.atom)
      if ext.len >= 2 and ext[0] == '_' and ext[1] == '_': continue
      if isProvision(ext):
        if not mapHas(provisionsNeeded, ext): provisionsNeeded.add ext
        continue
      stubs.add procSignature(pn) & ";"
      continue
    # `static inline` procs have internal linkage: each TU that uses one must
    # carry its own full definition. Emit a prototype up-front (so calls from
    # other inline bodies resolve regardless of order) plus the full body.
    if hasPragma(pp.pragmas, ["inline"]) and pp.body != nil:
      stubs.add procSignature(pn) & ";"
      foreignDefs.add genProc(pn)
      continue
    stubs.add "extern " & procSignature(pn) & ";"
  for gn in foreignGlobals:
    if hasPragma(gn.kids[1], ["nodecl", "header"]): continue
    if hasPragma(gn.kids[1], ["importc", "importcpp"]): continue
    let nm = declName(gn.kids[0].atom, gn.kids[1])
    stubs.add "extern " & declare(gn.kids[2], nm) & ";"

  # globals + deferred initializers
  var data: seq[string] = @[]
  var inits: seq[string] = @[]
  for g in globals:
    if hasPragma(g.kids[1], ["nodecl", "importc", "importcpp", "header"]): continue
    let info = genGlobal(g)
    data.add info.decl
    if info.needsInit:
      inits.add symName(info.nameAtom) & " = " & genExpr(info.value) & ";"
  for s in topStmts:
    let c = genStmt(s)
    if c.len > 0: inits.add c

  # C headers pulled in by importc procs/globals/types -> real #includes.
  var headers: seq[string] = @[]
  for p in procs: addHeaders(procParts(p).pragmas, headers)
  for g in globals: addHeaders(g.kids[1], headers)
  for td in types: addHeaders(findTag(td, "pragmas"), headers)
  for p in foreignProcs: addHeaders(procParts(p).pragmas, headers)
  for g in foreignGlobals: addHeaders(g.kids[1], headers)
  for td in foreignTypes: addHeaders(findTag(td, "pragmas"), headers)

  # libc-backed implementations for no-header importc runtime symbols; their
  # header needs are folded into the #include set.
  var provisions: seq[string] = @[]
  for name in provisionsNeeded:
    let hneed = provisionNeeds(name)
    if hneed.len > 0 and not mapHas(headers, hneed): headers.add hneed
    provisions.add provisionImpl(name)

  var outp = ""
  if headers.len > 0:
    var hs: seq[string] = @[]
    for h in headers:
      if h.len > 0 and h[0] == '<': hs.add "#include " & h
      else: hs.add "#include \"" & h & "\""
    outp.add "/* --- imported C headers --- */\n" & joinSeq(hs, "\n") & "\n\n"
  outp.add "/* --- error/overflow flags --- */\nstatic _Thread_local NB8 LENGC_ERR_;\nstatic _Thread_local NB8 LENGC_OVF_;\n\n"
  if fwdDecls.len > 0:
    outp.add "/* --- forward type declarations --- */\n" & joinSeq(fwdDecls, "\n") & "\n\n"
  if typeDecls.len > 0:
    outp.add "/* --- types --- */\n" & joinSeq(typeDecls, "\n") & "\n\n"
  if protos.len > 0:
    outp.add "/* --- prototypes --- */\n" & joinSeq(protos, "\n") & "\n\n"
  if stubs.len > 0:
    outp.add "/* --- cross-module declarations --- */\n" & joinSeq(stubs, "\n") & "\n\n"
  if foreignDefs.len > 0:
    outp.add "/* --- cross-module inline definitions --- */\n" & joinSeq(foreignDefs, "\n\n") & "\n\n"
  if provisions.len > 0:
    outp.add "/* --- runtime provisions (no-header importc) --- */\n" & joinSeq(provisions, "\n") & "\n\n"
  if data.len > 0:
    outp.add "/* --- globals --- */\n" & joinSeq(data, "\n") & "\n\n"
  if defs.len > 0:
    outp.add "/* --- procedures --- */\n" & joinSeq(defs, "\n\n") & "\n\n"
  if inits.len > 0:
    outp.add "static void __attribute__((constructor)) aowlc_init(void) {\n" & joinSeq(inits, "\n") & "\n}\n"
  return indentC(outp)

# ---------------------------------------------------------------------------
# build an AST from the streaming cursor
# ---------------------------------------------------------------------------
# On-disk own-module symbols use an empty trailing hash slot (`fib.1.`); the
# loader (nifreader) expands that empty slot to the module suffix
# (`fib.1.fib`). The oracle reads the RAW on-disk form, so strip the suffix the
# loader appended to recover it — matching mangleToC's input byte-for-byte.
proc stripModuleSuffix(s: string): string =
  ## Nimony's real mangling KEEPS the module suffix: the loader (nifreader)
  ## expands an own-module symbol's empty trailing hash slot (`ini.0.`) to the
  ## module basename (`ini.0.fibdncrrv`), which is exactly what nimony's own C
  ## backend emits. Stripping it made a symbol's definition (`X60Qini_0_`)
  ## disagree with cross-module uses (`X60Qini_0_fibdncrrv`) and collide across
  ## modules, so we keep the fully-qualified name verbatim.
  result = s

proc buildNode(c: var Cursor): Node =
  case c.kind
  of ParLe:
    result = Node(kind: nkList, tag: pool.tags[c.tagId])
    inc c
    while c.kind != ParRi:
      result.kids.add buildNode(c)
    consumeParRi c
  of ParRi:
    inc c
    result = nil
  of DotToken:
    result = Node(kind: nkAtom, atom: ".")
    inc c
  of Symbol:
    result = Node(kind: nkAtom, atom: stripModuleSuffix(pool.syms[c.symId]))
    inc c
  of SymbolDef:
    result = Node(kind: nkAtom, atom: stripModuleSuffix(pool.syms[c.symId]), def: true)
    inc c
  of Ident:
    result = Node(kind: nkAtom, atom: pool.strings[c.litId])
    inc c
  of IntLit:
    result = Node(kind: nkAtom, atom: $pool.integers[c.intId])
    inc c
  of UIntLit:
    result = Node(kind: nkAtom, atom: $pool.uintegers[c.uintId] & "u")
    inc c
  of FloatLit:
    result = Node(kind: nkAtom, atom: $pool.floats[c.floatId])
    inc c
  of StringLit:
    result = Node(kind: nkStr, strVal: pool.strings[c.litId])
    inc c
  of CharLit:
    result = Node(kind: nkChar, chrVal: ord(c.charLit))
    inc c
  else:
    inc c
    result = nil

proc emitModuleBody*(root: var Cursor): string =
  resetEmitter()
  let tree = buildNode(root)
  result = emitUnit(classify(tree))
